# Generated by Django 4.0.5 on 2022-06-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_bio_alter_user_gender_alter_user_language'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
