# Generated by Django 4.0.5 on 2022-06-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_conversation_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversations',
            new_name='conversation',
        ),
    ]
